services:
  metrics-frontend:
    build: .
    container_name: metrics-frontend
    hostname: web-server-2
    restart: unless-stopped
    ports:
      - "10.0.0.3:5173:5173"
    security_opt:
      - apparmor:unconfined
